/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2010 Synopsys, Inc. and/or its affiliates
 * Synopsys DesignWare HDMI TX controller driver
 */

// SYSTEM - FPGA SYSTEM IS A HAPS-DX7
#define PROTO_HDMI_TX_TARGET_FPGA_SYSTEM 0

// SYSTEM - SYSTEM CPU ARCHITECTURE IS 32-BIT
#define PROTO_HDMI_TX_HOST_SYSTEM_CPU_ARCH 32

// SYSTEM - FPGA DESIGN HAS AN INTEGRATION WITH HIB(HOST INTERFACE BRIDGE) THE LEVEL
#define PROTO_HDMI_TX_SYSTEM_INTEGRATION_LEVEL 2

// SYSTEM - DESIGN AXI BUS IS CONNECTED TO THE HIB
#define PROTO_HDMI_TX_HIB_HOST_INTERFACE 0

// SYSTEM - SYSTEM BASE ADDRESS
#define PROTO_HDMI_TX_SYSTEM_BASE_ADDRESS 0xD0000000

// SYSTEM - ARC SDP AXI TUNNEL PHYSICALLY LOCATED ON CONNECTORS J7-8. (NOT RELEVANT FOR SW)
#define PROTO_HDMI_TX_AXI_TUNNEL_ARC_SDP_HT3_CONNECTOR 0

// DW_AXI - DESIGN IS AXI3 COMPLIANT
#define PROTO_HDMI_TX_HOST_INTERFACE_SPEC 0

// DW_AXI - AXI DATA WIDTH
#define PROTO_HDMI_TX_AXI_DATA_WIDTH 32

// AXI ADDRESS WIDTH
#define PROTO_HDMI_TX_AXI_ADDRESS_WIDTH 32

// DW_AXI - NUMBER OS AXI MASTERS IS 1
#define PROTO_HDMI_TX_AXI_NUM_MASTERS 1

// DW_AXI - NUMBER OSF AXI SLAVES IS 1
#define PROTO_HDMI_TX_AXI_NUM_SLAVES 1

// DW_AXI - START ADDRESS OF DW_X2P AXI SLAVE BLOCK
#define PROTO_HDMI_TX_AXI_SLV_DW_AXI_X2P_ADRESS_START 0x00000000

// DW_AXI - END ADDRESS OF DW_X2P AXI SLAVE BLOCK
#define PROTO_HDMI_TX_AXI_SLV_DW_AXI_X2P_ADRESS_END 0x000BFFFF

// DW_AXI - START ADDRESS OF HIB AXI SLAVE BLOCK (NOT THE FINAL VALUE)
#define PROTO_HDMI_TX_AXI_SLV_DW_AXI_HIB_ADRESS_START 0x30000000

// DW_AXI - END ADDRESS OF HIB AXI SLAVE BLOCK (NOT THE FINAL VALUE)
#define PROTO_HDMI_TX_AXI_SLV_DW_AXI_HIB_ADRESS_END 0x3FFFFFFF

// DW_X2P - START ADDRESS OF DW_X2P APB SLAVE DWC_HDMI_TX 
#define PROTO_HDMI_TX_APB_HDMITXCORE_ADDRESS_START 0x00000000

// DW_X2P - END ADDRESS OF DW_X2P APB SLAVE DWC_HDMI_TX 
#define PROTO_HDMI_TX_APB_HDMITXCORE_ADDRESS_END 0x0003FFFF

// DW_X2P - START ADDRESS OF DW_X2P APB SLAVE CRM - CLOCK MANAGER
#define PROTO_HDMI_TX_APB_CRM_CLKMGR_ADDRESS_START 0x00040000

// DW_X2P - END ADDRESS OF DW_X2P APB SLAVE CRM - CLOCK MANAGER
#define PROTO_HDMI_TX_APB_CRM_CLKMGR_ADDRESS_END 0x0004FFFF

// DW_X2P - START ADDRESS OF DW_X2P APB SLAVE CRM - RESET MANAGER
#define PROTO_HDMI_TX_APB_CRM_RSTMGR_ADDRESS_START 0x00050000

// DW_X2P - END ADDRESS OF DW_X2P APB SLAVE CRM - RESET MANAGER
#define PROTO_HDMI_TX_APB_CRM_RSTMGR_ADDRESS_END 0x0005FFFF

// DW_X2P - START ADDRESS OF DW_X2P APB SLAVE DW_APB_ICTL
#define PROTO_HDMI_TX_APB_ICTL_ADDRESS_START 0x00060000

// DW_X2P - END ADDRESS OF DW_X2P APB SLAVE DW_APB_ICTL
#define PROTO_HDMI_TX_APB_ICTL_ADDRESS_END 0x0006FFFF

// DW_X2P - START ADDRESS OF DW_X2P APB SLAVE HDCP BLOCK
#define PROTO_HDMI_TX_APB_HDCP_ADDRESS_START 0x00070000

// DW_X2P - END ADDRESS OF DW_X2P APB SLAVE HDCP BLOCK
#define PROTO_HDMI_TX_APB_HDCP_ADDRESS_END 0x0007FFFF

// DW_X2P - START ADDRESS OF DW_X2P APB SLAVE VIDEOBRIDGE
#define PROTO_HDMI_TX_APB_VIDEOBRIDGE_ADDRESS_START 0x00080000

// DW_X2P - END ADDRESS OF DW_X2P APB SLAVE VIDEO BRIDGE
#define PROTO_HDMI_TX_APB_VIDEOBRIDGE_ADDRESS_END 0x0008FFFF

// DW_X2P - START ADDRESS OF DW_X2P APB SLAVE  AUDIO BRIDGE
#define PROTO_HDMI_TX_APB_AUDIOBRIDGE_ADDRESS_START 0x00090000

// DW_X2P - END ADDRESS OF DW_X2P APB SLAVE AUDIO BRIDGE
#define PROTO_HDMI_TX_APB_AUDIOBRIDGE_ADDRESS_END 0x0009FFFF

// DW_X2P - START ADDRESS OF DW_X2P APB SLAVE HT3 INTERFACE
#define PROTO_HDMI_TX_APB_HT3_IF_ADDRESS_START 0x000A0000

// DW_X2P - END ADDRESS OF DW_X2P APB SLAVE HT3 INTERFACE
#define PROTO_HDMI_TX_APB_HT3_IF_ADDRESS_END 0x000AFFFF

// DW_X2P - START ADDRESS OF DW_X2P APB SLAVE TX PHY INTERFACE
#define PROTO_HDMI_TX_APB_TXPHY_IF_ADDRESS_START 0x000B0000

// DW_X2P - END ADDRESS OF DW_X2P APB SLAVE TX PHY INTERFACE
#define PROTO_HDMI_TX_APB_TXPHY_IF_ADDRESS_END 0x000BFFFF

// DWC_HDMI_TX - AUDIO INTERFACES: I2S and SPDIF audio interfaces (designated as DOUBLE interface)
#define PROTO_HDMI_TX_HDMITXCC_AUDIO_IF 4

// DWC_HDMI_TX - AUDIO DMA ADDRESS WIDTH set to 7 bit
#define PROTO_HDMI_TX_HDMITXCC_HDMI_TX_AHBDMAAUD_FIFO_ADDRWITH 7

// DWC_HDMI_TX - S/PDIF DATA RECOVERY UNIT (DRU) IS BYPASSED
#define PROTO_HDMI_TX_HDMITXCC_HTX_SPDIFBYPDRU 1

// DWC_HDMI_TX - HIGH BIT RATE (HBR) AUDIO RECEPTION THROUGH THE EXISTING S/PDIF INTERFACE IS ENABLED
#define PROTO_HDMI_TX_HDMITXCC_HBR_ON_SPDIF 1

// DWC_HDMI_TX - HDMI 2.0 SPECIFICATION FEATURES ARE INCLUDED
#define PROTO_HDMI_TX_HDMITXCC_DWC_HDMI_TX_20 1

// DWC_HDMI_TX - HDMI 1.4 SPECIFICATION FEATURES ARE INCLUDED
#define PROTO_HDMI_TX_HDMITXCC_DWC_HDMI_TX_14 1

// DWC_HDMI_TX - HDCP IS ENABLED
#define PROTO_HDMI_TX_HDMITXCC_HDCP 1

// DWC_HDMI_TX - PRE-PROGRAMMED DPK KEYS ARE PRESENT ON DESIGN. NOT SOFTWARE CONFIGURABLE
#define PROTO_HDMI_TX_HDMITXCC_DWC_HDMI_HDCP_DPK_ROMLESS 0

// DWC_HDMI_TX - EXTERNAL DPK IS 8-BIT INTERFACE
#define PROTO_HDMI_TX_HDMITXCC_DWC_HDMI_HDCP_DPK_8BIT 1

// DWC_HDMI_TX - HDCP ENGINE IS VERSION 1.4 ONLY
#define PROTO_HDMI_TX_HDMITXCC_HTX_HDCP_TYPE 0

// DWC_HDMI_TX - COLOR SPACE CONVERTER (CSC) IS ENABLED
#define PROTO_HDMI_TX_HDMITXCC_CSC 1

// DWC_HDMI_TX - CONSUMER ELECTRONICS CONTROL (CEC) IS ENABLED
#define PROTO_HDMI_TX_HDMITXCC_CEC 1

// DWC_HDMI_TX - INTERNAL PIXEL REPETITION IS ENABLED
#define PROTO_HDMI_TX_HDMITXCC_DWC_HDMI_TX_INTPREPEN 1

// DWC_HDMI_TX - THE CORE USES A NON-SYNOPSYS EXTERNAL PHY
#define PROTO_HDMI_TX_HDMITXCC_PHY_EXTERNAL 1

// DWC_HDMI_TX - NOT USING FPGA SYNTHESIS
#define PROTO_HDMI_TX_HDMITXCC_HDMITX_FPGA_SYNTHESIS 0

// DWC_HDMI_TX - INTERNAL HDCP MEMORIES USED IN FPGA ASSEMBLY
#define PROTO_HDMI_TX_HDMITXCC_FPGA_HDCP_MEM 2

// DWC_HDMI_TX - Number of synchronizing flip-flop stages in reset synchronizers: 2
#define PROTO_HDMI_TX_HDMITXCC_HDMIRSYNCDEPTH 2

// DWC_HDMI_TX - Number of synchronizing flip-flop stages in data synchronizers:2
#define PROTO_HDMI_TX_HDMITXCC_HDMIDATASYNCDEPTH 2

// HT3 INTERFACE - CEAVID DATA WIDTH PRESENT ON HT3 CABLE TO BE CONNECTED TO AN EXTERNAL MEDIA SOURCE
#define PROTO_HDMI_TX_HT3_IF_CEAVID_DATA_WIDTH 48

// HT3 INTERFACE - I2S DATA WIDTH PRESENT ON HT3 CABLE TO BE CONNECTED TO AN EXTERNAL MEDIA SOURCE
#define PROTO_HDMI_TX_HT3_IF_I2S_DATA_WIDTH 4

// HT3 INTERFACE - SPDIF DATA WIDTH PRESENT ON HT3 CABLE TO BE CONNECTED TO AN EXTERNAL MEDIA SOURCE
#define PROTO_HDMI_TX_HT3_IF_SPDIF_DATA_WIDTH 4

// TX PHY INTERFACE - CONNECTED TO THE FPGA IS HDMI-MHL TX COMBO PHY
#define PROTO_HDMI_TX_PHY_TYPE 1

// CRM - TX PHY TMDS clock source to TMDS clock in feedback is made through a global buffer
#define PROTO_HDMI_TX_CRM_TMDSCLK_SRC2IN_FB_TYPE 1
