#ifndef SELF_TEST_SYS_INCLUDE_H_
#define SELF_TEST_SYS_INCLUDE_H_

CVI_S32 CVI_SYS_FIFO_TEST(void);
CVI_S32 CVI_SYS_FMT_TEST(void);
CVI_S32 CVI_SYS_ION_TEST(void);
CVI_S32 CVI_VB_TEST(void);
CVI_S32 CVI_SYS_BIND_TEST(void);

#endif // SELF_TEST_SYS_INCLUDE_H_
