// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (c) 2010 Synopsys, Inc. and/or its affiliates
 * Synopsys DesignWare HDMI TX controller driver
 */

#include "api/api.h"
#include "util/log.h"
#include "util/general_ops.h"
#include "core/control.h"
#include "core/main_controller.h"
#include "core/video.h"
#include "core/audio.h"
#include "core/packets.h"
#include "core/irq.h"
#include "hdcp/hdcp.h"
#include "edid/edid.h"
#include "util/error.h"
#include "bsp/board.h"
#include "identification.h"

void hdmitx_api_init(hdmi_tx_dev_t * dev, char * name)
{
	memset(dev, 0, sizeof(hdmi_tx_dev_t));
	memcpy(dev->device_name, name, sizeof(dev->device_name));
}

void api_set_hdmi_ctrl(hdmi_tx_dev_t *dev, videoParams_t * video, hdcpParams_t * hdcp)
{
	video_mode_t hdmi_on = 0;
	struct hdmi_tx_ctrl *tx_ctrl = &dev->snps_hdmi_ctrl;

	hdmi_on = video->mHdmi;
	tx_ctrl->hdmi_on = (hdmi_on == HDMI) ? 1 : 0;
	tx_ctrl->pixel_clock = videoParams_GetPixelClock(dev,video);
	if (video->mEncodingOut == YCC422)
		tx_ctrl->color_resolution = 8;
	else
		tx_ctrl->color_resolution = video->mColorResolution;
	tx_ctrl->pixel_repetition = PIXEL_REPETITION_OFF;
	tx_ctrl->encoding = video->mEncodingOut;
	tx_ctrl->csc_on = 1;
	tx_ctrl->audio_on = (hdmi_on == HDMI) ? 1 : 0;
}

int api_Configure(hdmi_tx_dev_t *dev, videoParams_t * video, audioParams_t * audio,
		  productParams_t * product, hdcpParams_t * hdcp, u16 phy_model)
{
	int success = TRUE;

	if (!dev) {
		LOGGER(SNPS_ERROR, "%s: Device pointer invalid", __func__);
		return FALSE;
	}

	if (!video || !audio || !product || !hdcp) {
		LOGGER(SNPS_ERROR, "%s: Argument Invalid received: video=%x; audio=%x; product=%x; hdcp=%x", __func__, video, audio, product, hdcp);
		return FALSE;
	}

	if(dev->snps_hdmi_ctrl.hpd == 0){
		LOGGER(SNPS_WARN, "Trying to configure HDMI TX without a sink");
		return TRUE;
	}

	api_set_hdmi_ctrl(dev, video, hdcp);

	phy_standby(dev);

	api_avmute(dev, TRUE);


	// Disable interrupts
	irq_mute(dev);

	success = video_Configure(dev, video);
	if (success == FALSE) {
		LOGGER(SNPS_ERROR, "%s:Could not configure video", __func__);
	}

	// Audio - Workaround
	audio_Initialize(dev);
	success = audio_Configure(dev, audio);
	if(success == FALSE){
		LOGGER(SNPS_ERROR, "%s:Audio not configured", __func__);
	}

	// Packets
	success = packets_Configure(dev, video, product);
	if (success == FALSE) {
		LOGGER(SNPS_ERROR, "%s:Could not configure packets", __func__);
	}

	// Pixel Clocks
#ifndef PHY_THIRD_PARTY
	//don't configure Pixel clock in case of ThirdParty Phy - the clock is generated by the PHY
	success = board_PixelClock(dev);
	if (success == FALSE) {
		LOGGER(SNPS_ERROR, "%s:Could not configure Pixel Clock", __func__);
		return FALSE;
	}
#endif

	mc_enable_all_clocks(dev);
	snps_sleep(100);

	// success = phy_configure(dev, phy_model);
	// if (success == FALSE) {
	// 	LOGGER(SNPS_ERROR, "%s:Could not configure PHY", __func__);
	// }

	// Disable blue screen transmission after turning on all necessary blocks (e.g. HDCP)
	fc_force_output(dev, FALSE);

	//TODO:This should be called at HPD event
	// HDCP is PHY independent
	if (hdcp_initialize(dev) != TRUE) {
		LOGGER(SNPS_ERROR, "%s:Could not initialize HDCP", __func__);
	}
	snps_sleep(200);
	success = hdcp_configure(dev, hdcp, video);
	if (success == FALSE) {
		LOGGER(SNPS_ERROR, "%s:Could not configure HDCP", __func__);
	}

	// enable interrupts
	irq_unmute(dev);

	api_avmute(dev, FALSE);

	snps_sleep(1);

	return success;
}

int api_Standby(hdmi_tx_dev_t *dev)
{
	control_Standby(dev);
	phy_standby(dev);

	dev->snps_hdmi_ctrl.hdmi_on = 0;
	dev->snps_hdmi_ctrl.pixel_clock = 0;
	dev->snps_hdmi_ctrl.color_resolution = 0;
	dev->snps_hdmi_ctrl.pixel_repetition = 0;
	dev->snps_hdmi_ctrl.csc_on = 0;
	dev->snps_hdmi_ctrl.audio_on = 0;

	return TRUE;
}

void api_avmute(hdmi_tx_dev_t *dev, int enable)
{
	packets_AvMute(dev, enable);
	hdcp_av_mute(dev, enable);
}
